@host = https://localhost:7048
@base = https://jsonplaceholder.typicode.com
@accept = application/json


### Get all posts
GET {{host}}/posts
Accept: {{accept}}

### Get post
GET {{host}}/posts/3
Accept: {{accept}}