@host = https://localhost:7180
@base = https://jsonplaceholder.typicode.com
@accept = application/json


### Get all posts
GET {{base}}/posts
Accept: {{accept}}

### Get post
GET {{base}}/posts/3
Accept: {{accept}}